# Generated by Django 2.2 on 2019-06-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=1500)),
                ('audience', models.CharField(max_length=1500)),
                ('status', models.CharField(max_length=50)),
                ('proposal_type', models.CharField(choices=[('talk', 'Talk'), ('workshop', 'Workshop')], max_length=25)),
                ('proposal_section', models.CharField(max_length=1500)),
                ('pre_requisites', models.TextField(max_length=1500)),
                ('current_urls', models.TextField(max_length=1500)),
                ('speaker_info', models.TextField(max_length=1500)),
                ('speaker_links', models.TextField(max_length=1500)),
            ],
        ),
    ]
